version: "3.7"
services:
  admin1:
    image: kamicode/e-book-docker:v1
    ports:
      - "9090:9090" #端口映射
    restart: always
    expose:
      - 9090        #暴露容器端口
    depends_on:
      - app_db
      - redis1
      - neo4j1
      - mongodb1
  admin2:
    image: kamicode/e-book-docker:v1
    ports:
      - "9091:9090" #端口映射
    restart: always
    expose:
      - 9091        #暴露容器端口
    depends_on:
      - app_db
      - redis1
      - neo4j1
      - mongodb1
  nginx1:
    image: nginx
    volumes:
           - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
          - "80:80"
    expose:
          - "80"
    depends_on:
      - admin1
      - admin2

  mongodb1:
    image: "mongo:5.0"
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234


  app_db:
    image: mysql:8.0.23

    hostname: testt
    command:
    # MySQL8的密码验证方式默认是 caching_sha2_password，但是很多的连接工具还不支持该方式
    # 就需要手动设置下mysql的密码认证方式为以前的 mysql_native_password 方式
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --init-file /docker-entrypoint-initdb.d/init.sql  #attention here
    # docker的重启策略：在容器退出时总是重启容器，但是不考虑在Docker守护进程启动时就已经停止了的容器
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password # root用户的密码
      MYSQL_DATABASE: bookstore
      MYSQL_ROOT_HOST: '%'

    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./db:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./log:/logs
      - ./init:/docker-entrypoint-initdb.d

  redis1:
    image: redis
    ports:
         - "6379:6379"
    expose:
         - "6379"

  neo4j1:
    image: neo4j:4.1.3
    volumes:
        - /opt/neo4j/data/conf:/conf
        - /opt/neo4j/data/data:/data
        - /opt/neo4j/data/import:/import
        - /opt/neo4j/data/logs:/logsneo4j
    environment:
        NEO4J_AUTH: none
    ports:
        - 7687:7687 #Bolt
        - 7474:7474 #HTTP


